services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labora_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://labora:labora@db:5432/labora
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    container_name: labora_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: labora
      POSTGRES_PASSWORD: labora
      POSTGRES_DB: labora
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labora -d labora"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
